apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    meta.helm.sh/release-name: uho
    meta.helm.sh/release-namespace: uho
  labels:
    app.kubernetes.io/managed-by: Helm
  name: nginx-ingress
  namespace: uho
spec:
  rules:
    - http:
        paths:
          - path: /v1/patients
            pathType: Prefix
            backend:
              service:
                name: uho-patient
                port:
                  number: 80
          - path: /v1/providers
            pathType: Prefix
            backend:
              service:
                name: uho-provider
                port:
                  number: 80
          - path: /v1/appointments
            pathType: Prefix
            backend:
              service:
                name: uho-appointment
                port:
                  number: 80
          - path: /v1/encounters
            pathType: Prefix
            backend:
              service:
                name: uho-encounter
                port:
                  number: 80                  
          - path: /home
            pathType: Prefix
            backend:
              service:
                name: uho-frontend
                port:
                  number: 80
          - path: /oauth
            pathType: Prefix
            backend:
              service:
                name: uho-frontend
                port:
                  number: 80
          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: uho-frontend
                port:
                  number: 80