title: "United Healthcare Organisation"
description: "UHO: Healthcare reference application"
informationalText: "This stack provision all the necessary infrastructure required to run UHO: Healthcare Reference Application"
schemaVersion: 1.1.0
version: "20190304"

logoUrl: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMTI4IDEyOCI+CiAgPGRlZnM+CiAgICA8ZmlsdGVyIGlkPSJQYXRoXzI3IiB4PSIwIiB5PSIwIiB3aWR0aD0iNjguMjciIGhlaWdodD0iNjIuOTUxIiBmaWx0ZXJVbml0cz0idXNlclNwYWNlT25Vc2UiPgogICAgICA8ZmVPZmZzZXQgZHg9IjEiIGR5PSIzIiBpbnB1dD0iU291cmNlQWxwaGEiLz4KICAgICAgPGZlR2F1c3NpYW5CbHVyIHN0ZERldmlhdGlvbj0iMyIgcmVzdWx0PSJibHVyIi8+CiAgICAgIDxmZUZsb29kIGZsb29kLW9wYWNpdHk9IjAuNTAyIi8+CiAgICAgIDxmZUNvbXBvc2l0ZSBvcGVyYXRvcj0iaW4iIGluMj0iYmx1ciIvPgogICAgICA8ZmVDb21wb3NpdGUgaW49IlNvdXJjZUdyYXBoaWMiLz4KICAgIDwvZmlsdGVyPgogICAgPGZpbHRlciBpZD0icGF0aDUiIHg9IjE3LjYzNyIgeT0iMTEuNCIgd2lkdGg9IjMyLjUzNyIgaGVpZ2h0PSIzOS4xNzMiIGZpbHRlclVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CiAgICAgIDxmZU9mZnNldCBkeT0iMyIgaW5wdXQ9IlNvdXJjZUFscGhhIi8+CiAgICAgIDxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249IjMiIHJlc3VsdD0iYmx1ci0yIi8+CiAgICAgIDxmZUZsb29kIGZsb29kLW9wYWNpdHk9IjAuMjc1Ii8+CiAgICAgIDxmZUNvbXBvc2l0ZSBvcGVyYXRvcj0iaW4iIGluMj0iYmx1ci0yIi8+CiAgICAgIDxmZUNvbXBvc2l0ZSBpbj0iU291cmNlR3JhcGhpYyIvPgogICAgPC9maWx0ZXI+CiAgPC9kZWZzPgogIDxnIGlkPSJHcm91cF81MCIgZGF0YS1uYW1lPSJHcm91cCA1MCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTIzIC0xNzUpIj4KICAgIDxnIGlkPSJHcm91cF80NCIgZGF0YS1uYW1lPSJHcm91cCA0NCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE3IC0yMjcpIj4KICAgICAgPGcgaWQ9ImFpbHVyb3BoaWxlIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSg1Ni4xNDYgNDI0KSI+CiAgICAgICAgPHBhdGggaWQ9IlBhdGhfMjIiIGRhdGEtbmFtZT0iUGF0aCAyMiIgZD0iTTkyLjQxOSwzOS45M2MxLjM2Ni0zLjc1MywyLjQ1Mi05LjI4OC0uMTM0LTE0LjM0MkExNC4xNTcsMTQuMTU3LDAsMCwxLDkwLjgsMTkuMDc3Yy4wMzYtNi4wNzEuMTI4LTEyLjM5NS4yLTE2LjYzMUEyLjQsMi40LDAsMCwwLDg2Ljg4LjcyNmwtOS41MTUsOS43MjZhMjQuNDcxLDI0LjQ3MSwwLDAsMC0xNC4yOTMsMS4wMzVjLTIuNjg1LTIuNjA2LTcuNzE1LTcuMDI5LTEwLjYtOS41NGEyLjM3LDIuMzcsMCwwLDAtMi42MjMtLjM1MiwyLjQsMi40LDAsMCwwLTEuMzU4LDIuMjc1bC42ODEsMTUuMTUyYTQyLjQ2LDQyLjQ2LDAsMCwxLS43NjksMTAuMjQzQTU4LjY2NCw1OC42NjQsMCwwLDAsNDcuMiw0My40NTksMjYuNzE2LDI2LjcxNiwwLDAsMCwzMi44NzksNDkuNWMtNy44MDYsNi4zMjItMTIuODU3LDE2LjYyMS0xNS4wMTIsMzAuNjEzYTEuMTUsMS4xNSwwLDAsMCwyLjI3NC4zNUMyMi4yMDcsNjcuMDU3LDI2Ljk4LDU3LjI0MSwzNC4zMjcsNTEuMjljNi41NjgtNS4zMTksMTIuOS01LjU4OSwxNC4xLTUuNTg5YTEuMTUsMS4xNSwwLDAsMCwxLjE0Ni0xLjI0OCw1NC41NTksNTQuNTU5LDAsMCwxLDEuMDg4LTE0LjczNyw0NC43NDgsNDQuNzQ4LDAsMCwwLC44MTItMTAuOEw1MC43OTIsMy43NjZhLjA5MS4wOTEsMCwwLDEsLjA1OS0uMS4wODcuMDg3LDAsMCwxLC4xMTIuMDE1YzMuMDY3LDIuNjcxLDguNTc2LDcuNTE3LDExLjAyLDkuOTYyYTEuMTUsMS4xNSwwLDAsMCwxLjI0OC4yNTIsMjIuMDU5LDIyLjA1OSwwLDAsMSwxNC4xMDctMS4wNiwxLjE1MSwxLjE1MSwwLDAsMCwxLjE5Mi0uMjg1TDg4LjUyNCwyLjMzNWEuMDg5LjA4OSwwLDAsMSwuMTE2LS4wMjQuMDg2LjA4NiwwLDAsMSwuMDYzLjFjLS4wNzIsNC4yNDItLjE2NCwxMC41NzUtLjIsMTYuNjU2YTE2LjQ2OCwxNi40NjgsMCwwLDAsMS43MzMsNy41NzNjMi4yMDgsNC4zMTYsMS4yMyw5LjE4My4wMiwxMi41MDdhMTYuNzUyLDE2Ljc1MiwwLDAsMC0uNTA2LDkuNzVjMS42NTQsNi43NDQsMy4zNTgsMTkuOS0zLjgxNywzMi4yMjRhMS4xNSwxLjE1LDAsMSwwLDEuOTg4LDEuMTU3YzcuNTgxLTEzLjAyNCw1LjgtMjYuODQ4LDQuMDYzLTMzLjkzQTE0LjQ2MSwxNC40NjEsMCwwLDEsOTIuNDE5LDM5LjkzWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCAwKSIvPgogICAgICAgIDxwYXRoIGlkPSJQYXRoXzIzIiBkYXRhLW5hbWU9IlBhdGggMjMiIGQ9Ik0yNDQuMDA4LDEyOS42ODVhMS4xNSwxLjE1LDAsMCwwLDIuMywwLDQuNyw0LjcsMCwwLDAtOS4zOTQsMCwxLjE1LDEuMTUsMCwwLDAsMi4zLDAsMi40LDIuNCwwLDAsMSw0Ljc5MywwWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE3Ny4wNjIgLTEwMS4wMjUpIi8+CiAgICAgICAgPHBhdGggaWQ9IlBhdGhfMjQiIGRhdGEtbmFtZT0iUGF0aCAyNCIgZD0iTTMyNS42MTQsMTI0Ljk4OGE0LjcsNC43LDAsMCwwLTQuNyw0LjcsMS4xNSwxLjE1LDAsMSwwLDIuMywwLDIuNCwyLjQsMCwwLDEsNC43OTMsMCwxLjE1LDEuMTUsMCwxLDAsMi4zLDBBNC43LDQuNywwLDAsMCwzMjUuNjE0LDEyNC45ODhaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMjQ0Ljk2IC0xMDEuMDI1KSIvPgogICAgICAgIDxwYXRoIGlkPSJQYXRoXzI1IiBkYXRhLW5hbWU9IlBhdGggMjUiIGQ9Ik0yNzQuOTU3LDE4Mi41MTdhMS4xNSwxLjE1LDAsMCwwLTEuMTUsMS4xNSwzLjMsMy4zLDAsMSwxLTYuNjA2LDAsMS4xNSwxLjE1LDAsMCwwLTIuMywwLDMuMywzLjMsMCwxLDEtNi42MDYsMCwxLjE1LDEuMTUsMCwwLDAtMi4zLDAsNS42LDUuNiwwLDAsMCwxMC4wNTcsMy40LDUuNiw1LjYsMCwwLDAsMTAuMDU3LTMuNEExLjE1LDEuMTUsMCwwLDAsMjc0Ljk1NywxODIuNTE3WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE5Mi40ODMgLTE0Ny41MjUpIi8+CiAgICAgIDwvZz4KICAgIDwvZz4KICAgIDxnIGlkPSJjb252ZXJzYXRpb24tc3BlZWNoLWJ1YmJsZXMtIiB0cmFuc2Zvcm09Im1hdHJpeCgwLjk5NSwgLTAuMTA1LCAwLjEwNSwgMC45OTUsIDMyLjI2NSwgMTk4LjYwMSkiPgogICAgICA8ZyB0cmFuc2Zvcm09Im1hdHJpeCgwLjk5LCAwLjEsIC0wLjEsIDAuOTksIC02LjgyLCAtMTAuNjgpIiBmaWx0ZXI9InVybCgjUGF0aF8yNykiPgogICAgICAgIDxwYXRoIGlkPSJQYXRoXzI3LTIiIGRhdGEtbmFtZT0iUGF0aCAyNyIgZD0iTTIzLjE1NC45MzVjMTIuNzg4LDAsMjMuMTU0LDguMTg5LDIzLjE1NCwxOC4yODdhMTYuMzY0LDE2LjM2NCwwLDAsMS02LjEzMiwxMi40Yy4xNDYsMy4xNzUuOCw3LjQ0NCwzLjExNiw5LjY0Ni00LjQyMiwwLTguOTUxLTIuOTI2LTExLjYzNi01LjAzNGEyOC40NjMsMjguNDYzLDAsMCwxLTguNSwxLjI3N0MxMC4zNjYsMzcuNTA5LDAsMjkuMzIsMCwxOS4yMjJTMTAuMzY2LjkzNSwyMy4xNTQuOTM1WiIgdHJhbnNmb3JtPSJtYXRyaXgoMC45OSwgLTAuMSwgMC4xLCAwLjk5LCA3LjksIDkuOTEpIiBvcGFjaXR5PSIwLjA5NyIvPgogICAgICA8L2c+CiAgICA8L2c+CiAgICA8ZyB0cmFuc2Zvcm09Im1hdHJpeCgxLCAwLCAwLCAxLCAyNC4zNiwgMTg4LjY5KSIgZmlsdGVyPSJ1cmwoI3BhdGg1KSI+CiAgICAgIDxwYXRoIGlkPSJwYXRoNS0yIiBkYXRhLW5hbWU9InBhdGg1IiBkPSJNMTYuODksMjQuNTA4aDBhMi4zNCwyLjM0LDAsMCwwLDIuNTI4LDIuMjEyQTMuMzMyLDMuMzMyLDAsMCwwLDIyLjEsMjUuM2MwLS4xNTgtLjE1OC0uNDc0LS4zMTYtLjQ3NHMtLjMxNi40NzQtMS4xMDYuNDc0Yy0xLjI2NCwwLTEuMjY0LTEuMjY0LTEuMjY0LTIuNjg2VjEyLjY1N2MtLjc5LDAtMS43MzguMzE2LTIuNTI4LjMxNlYyMy4wODZBNi4yMTksNi4yMTksMCwwLDEsMTIuNzgxLDI1LjNjLTEuOSwwLTIuMzctMS41OC0yLjM3LTMuNDc2VjE1LjY1OWMwLTEuMTA2LS4xNTgtMy0uMTU4LTMtLjk0OCwwLTEuOS4zMTYtMi42ODYuMzE2LDAsMCwuMzE2LDIuMzcuMzE2LDMuMzE4djUuODQ2YzAsMS45LjMxNiwzLjQ3Ni4zMTYsNC41ODIsMCwxLjktLjQ3NCwzLjMxOC0uNDc0LDUuMDU2QTIuMjE0LDIuMjE0LDAsMCwwLDkuNDYzLDMzLjgzYy43OSwwLDEuNDIyLS42MzIsMS40MjItMS45LDAtMS40MjItMS4xMDYtMy42MzQtMS4xMDYtNS42ODgsMC0uMTU4LjE1OC0uMzE2LjQ3NC0uMzE2YTIuMzY3LDIuMzY3LDAsMCwwLDEuOS43OUE1LjkyNCw1LjkyNCwwLDAsMCwxNi44OSwyNC41MDhaTTE2Ljg5LDI0LjUwOFoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDE5LjA3IDQuNzQpIi8+CiAgICA8L2c+CiAgPC9nPgo8L3N2Zz4=

source:
  type: quickstart

locale: "en"

variableGroups:
  - title: "General Configuration"
    variables:
      - app_name
      - idcs_url
      - idcs_admin_client_id
      - idcs_admin_client_secret
      - create_new_key
      - existent_kms_vault_id
      - existent_kms_key_id
      - current_user_ocid
      - smtp_username
      - smtp_password
      - auth_token
      - show_advanced_options

  - title: "Compartment Configuration"
    variables:
      - region
      - tenancy_ocid
      - compartment_ocid
    visible:
      and:
        - show_advanced_options
  - title: "CI/CD Configuration"
    variables:
      - create_devops_project
      - build_pipeline_stage_image
      - container_repository_is_public
      - create_external_connection
      - github_pat_token
      - github_repo_url
      - github_branch_name
    visible:
      and:
        - show_advanced_options
  - title: "OKE Configuration"
    variables:
      - cluster_endpoint_visibility
      - cluster_loadbalancer_visibility
      - cluster_workers_visibility
    visible: false
  - title: "Policy Configuration"
    variables:
      - create_compartment_policies
    visible: false
  - title: "OKE cluster encryption"
    variables:
      - use_cluster_encryption
    visible:
      and:
        - show_advanced_options
  - title: "Operator SSH configuration"
    variables:
      - generate_ssh_pair
      - private_key_path
      - public_key_path
    visible: false
  - title: "Network CIDRs"
    variables:
      - network_cidrs
    visible:
      and:
        - show_advanced_options
  - title: "Security Configuration"
    variables:
      - enable_cloud_guard
      - reporting_region
      - enable_waf
    visible:
      and:
        - show_advanced_options

variables:
  show_advanced_options:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options, allowing enable customer-managed encryption keys, choose your own compartment, select/unselect security services, and other advanced options"
    default: false

  app_name:
    type: string
    title: "App name"
    description: "Display name of the app"
    required: true

  current_user_ocid:
    type: string
    title: "Current user OCID"
    description: "Current user OCID"
    required: true
    visible: false

  smtp_username:
    type: string
    title: "SMTP username"
    description: "Username from SMTP credentials. This will be used for sending emails"
    required: true
    sensitive: true

  smtp_password:
    type: password
    title: "SMTP password"
    description: "Password from SMTP credentials. This will be used for sending emails"
    required: true
    sensitive: true

  auth_token:
    type: password
    title: "Auth token"
    description: "Authentication token to be used by streaming"
    required: true
    sensitive: true

  create_devops_project:
    type: boolean
    title: "Create devops project?"
    description: "Create devops project to manage ci/cd pipelines"
    required: true

  build_pipeline_stage_image:
    visible: #($create_devops_project == true)
      eq:
        - create_devops_project
        - true
    type: string
    title: "Build pipeline stage image"
    description: "The image used for build pipeline"
    required: true

  container_repository_is_public:
    type: boolean
    title: "Container repository is public?"
    description: "Whether the container repository used to fetch images for app is public?"
    required: true
    visible: false

  create_external_connection:
    visible: #($create_devops_project == true)
      eq:
        - create_devops_project
        - true
    type: boolean
    title: "Create external connection?"
    description: "Create external connection to connect to Github if you want to work with the devops pipeline"
    required: true

  github_pat_token:
    visible:
      eq:
        - create_external_connection
        - true
    type: string
    title: "Personal Access Token"
    description: "Personal Access Token to mirror your github repository"
    required: true


  github_repo_url:
    visible:
      eq:
        - create_external_connection
        - true
    type: string
    title: "Github repository url"
    description: "Your Github repository url which will be mirrored using external connection"
    required: true

  github_branch_name:
    visible:
      eq:
        - create_external_connection
        - true
    type: string
    title: "Github repository branch"
    description: "Github repository branch "
    required: false

  cluster_endpoint_visibility:
    type: boolean
    title: "Cluster endpoint visibility"
    description: "OKE cluster visibility Public or Private"
    required: true

  cluster_loadbalancer_visibility:
    type: boolean
    title: "Cluster load balancer visibility"
    description: "OKE cluster load balancer visibility Public or Private"
    required: true

  cluster_workers_visibility:
    type: boolean
    title: "Cluster worker nodes visibility"
    description: "OKE cluster worker nodes visibility Public or Private"
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which all the infra (except apigw) will be created"
    required: true
    visible: false

  normal_compartment_id:
    visible: false
    type: oci:identity:compartment:id
    title: "APIGW Compartment"
    description: "The compartment in which api gateway will be created"
    required: false

  create_compartment_policies:
    type: boolean
    title: "Create compartment policies"
    description: "Create compartment level policies"
    required: true

  use_cluster_encryption:
    type: boolean
    title: "Use OKE cluster encrpytion"
    description: "Use OKE cluster encryption using user managed keys from OCI vault"
    required: true

  create_new_key:
    type: boolean
    title: "Create a new KMS Key"
    description: "Creates a new OCI KMS Key inside a new OCI KMS Vault in the user's compartment"
    required: true

  existent_kms_vault_id:
    dependsOn:
      compartmentId: compartment_ocid
    visible: #(create_new_key == false)
      eq:
        - create_new_key
        - false
    type: oci:kms:vault:id
    title: "Existing vault"
    description: "Select an existing vault"
    required: true

  existent_kms_key_id:
    dependsOn:
      compartmentId: compartment_ocid
      vaultId: existent_kms_vault_id
    visible: #(create_new_key == false)
      eq:
        - create_new_key
        - false
    type: oci:kms:key:id
    title: "Existing key"
    description: "Select an existing key to encrypt data"
    required: true

  generate_ssh_pair:
    type: boolean
    title: "Generator ssh pair?"
    description: "Generate new ssh pair to ssh in operator"
    required: true

  private_key_path:
    type: string
    title: "Private key path"
    description: "Path of the private key used to ssh into operator"
    required: true

  public_key_path:
    type: string
    title: "Public key path"
    description: "Path of the public key to be used to ssh into operator"
    required: true

  network_cidrs:
    type: string
    title: "Network cidr blocks"
    description: "VCN and subnet cidr blocks"
    required: true
    visible: false

  deploy_using_msz_compartment:
    type: boolean
    title: "Deploy using Secure Zones?"
    description: "Deploys API Gateway and internet gateway in a separte compartment"
    required: false
    visible: false

  enable_cloud_guard:
    type: boolean
    title: "Enable cloud guard"
    description: "Enable and configure cloud guard"
    required: true

  enable_data_safe:
    type: boolean
    title: "Enable data safe"
    description: "Enable data safe and register databases as targets"
    required: false
    visible: false

  enable_waf:
    type: boolean
    title: "Enabled WAF"
    description: "Enabled web application firewall"
    required: true

  reporting_region:
    visible: #($enable_cloud_guard == true)
      eq:
        - enable_cloud_guard
        - true
    type: oci:identity:region:name
    title: "Cloud guard reporting region"
    description: "Select cloud guard reporting region. It is important to choose the right reporting region if Cloud guard is already enabled in your tenancy"
    required: true

  region:
    type: oci:identity:region:name
    title: "Region"
    description: "Region identifier"
    required: true
    visible: false

  tenancy_ocid:
    type: string
    title: "Tenancy ocid"
    description: "Tenancy ocid"
    required: true
    visible: false

  idcs_url:
    type: string
    title: "IDCS url"
    description: "IDCS url"
    required: true

  idcs_admin_client_id:
    type: string
    title: "IDCS admin client id"
    description: "Client id of the admin app configured in IDCS"
    required: true
    sensitive: true

  idcs_admin_client_secret:
    type: password
    title: "IDCS admin client secret"
    description: "Client secret of the admin app configured in IDCS"
    required: true
    sensitive: true

outputGroups:
  - title: UHO endpoints
    outputs:
      - uho_url

  - title: Login Usernames and passwords
    output:
      - patient_username
      - patient_password
      - provider_username
      - provider_password

  - title: Database passwords
    output:
      - autonomous_database_password
      - autonomous_json_database_password

  - title: SSH Keys
    output:
      - private_ssh_key
      - public_ssh_key

outputs:
  uho_url:
    type: link
    title: UHO URL
    displayText: Open UHO
    visible: true

  patient_username:
    type: string
    title: Patient username
    displayText: Patient username
    visible: true

  patient_password:
    type: string
    title: Patient password
    displayText: Patient password
    visible: true

  provider_username:
    type: string
    title: Provider username
    displayText: Provider username
    visible: true

  provider_password:
    type: string
    title: Provider password
    displayText: Provider password
    visible: true

  autonomous_database_password:
    type: string
    title: ADB password
    displayText: Autonomous relational DB password
    visible: true

  autonomous_json_database_password:
    type: string
    title: AJDB password
    displayText: Autonomous JSON DB password
    visible: true

  private_ssh_key:
    type: string
    title: Private ssh key
    displayText: Private key of the ssh key pair
    visible: true

  public_ssh_key:
    type: string
    title: Public ssh key
    displayText: Public key of the ssh key pair
    visible: true
