apiVersion: v1
kind: Secret
metadata:
  name: "ajdb-connection"
  namespace: uho
type: Opaque
data:
  ajdb-wallet-password: {{ .Values.secrets.ajdb.connection.wallet_password | b64enc }}
  ajdb-service: {{ .Values.secrets.ajdb.connection.ajdb_service | b64enc }}