apiVersion: v1
kind: Secret
metadata:
  name: "atp-patient-secret"
type: Opaque
data:
  atp-patient-username: {{ .Values.global.secrets.atp.patient.username | b64enc }}
  atp-patient-password: {{ .Values.global.secrets.atp.patient.password | b64enc }}