apiVersion: v1
kind: Service
metadata:
  name: {{ include "feedback.fullname" . }}
  labels: {{ include "feedback.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "feedback.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.pod.containerPort }}