micronaut:
  application:
    name: encounter
  security:
    enabled: false
  object-storage:
    oracle-cloud:
      default:
        namespace: '<your namespace name>'
        bucket: '<your bucket name>'
  metrics:
    enabled: false
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''

