micronaut:
  application:
    name: encounter
  security:
    token:
      jwt:
        signatures:
          static-jwks:
            key-type: "RSA"
            keys:
      roles-name: "scope"
    endpoints:
      logout:
        enabled: true
        get-allowed: true
    intercept-url-map-prepend-pattern-with-context-path: false
    intercept-url-map:
      - pattern: /v1/encounters
        httpMethod: POST
        access:
          - /patient
          - /provider
          - /service
      - pattern: /v1/encounters/*
        httpMethod: DELETE
        access:
          - /provider
      - pattern: /v1/encounters/*
        httpMethod: GET
        access:
          - /patient
          - /provider
          - /service
      - pattern: /v1/encounters/*
        httpMethod: PUT
        access:
          - /provider
      - pattern: /v1/encounters/codes
        httpMethod: GET
        access:
          - /patient
          - /provider
      - pattern: /v1/encounters/actions/search
        httpMethod: GET
        access:
          - /patient
          - /provider
  metrics:
    enabled: true
    export:
      oraclecloud:
        enabled: true
        namespace: uho_${micronaut.application.name}
        resourceGroup: mn_prod
        compartmentId:
  object-storage:
    oracle-cloud:
      default:
        namespace: ${OBJECT_STORAGE_NAMESPACE_NAME}
        bucket: ${OBJECT_STORAGE_BUCKET_NAME}

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/migrations.xml'
  enabled: true

otel:
  exporter:
    zipkin:
      url: ${TRACING_ZIPKIN_HTTP_URL:''}
      path: ${TRACING_ZIPKIN_HTTP_PATH:''}
oci:
  config:
