micronaut:
  application:
    name: encounter
  security:
    enabled: false
    token:
      jwt:
        secret:
          generator:
            secret:
              pleaseChangeThisSecretForANewOne
      roles-name: "scope"
    endpoints:
      logout:
        enabled: true
        get-allowed: true
    intercept-url-map-prepend-pattern-with-context-path: false
    intercept-url-map:
      - pattern: /v1/encounters
        httpMethod: POST
        access:
          - /patient
          - /provider
          - /service
      - pattern: /v1/encounters/*
        httpMethod: DELETE
        access:
          - /provider
      - pattern: /v1/encounters/*
        httpMethod: GET
        access:
          - /patient
          - /provider
          - /service
      - pattern: /v1/encounters/*
        httpMethod: PUT
        access:
          - /provider
      - pattern: /v1/encounters/codes
        httpMethod: GET
        access:
          - /patient
          - /provider
      - pattern: /v1/encounters/actions/search
        httpMethod: GET
        access:
          - /patient
          - /provider
  metrics:
    enabled: false
    export:
      oraclecloud:
        enabled: true
        namespace: uho_${micronaut.application.name}
        resourceGroup: mn_local
        compartmentId: "" #<Add compartment id here where metrics need to be posted>
datasources:
  default:
    ocid:
    walletPassword:
    username:
    password:
    dialect: ORACLE
    data-source-properties:
      oracle:
        jdbc:
          fanEnabled: false
oci:
  config:
    profile: DEFAULT