apiVersion: v1
kind: Secret
metadata:
  name: "apm"
  namespace: uho
type: Opaque
data:
  data_upload_endpoint: {{ .Values.secrets.apm.data_upload_endpoint | b64enc }}
  data_upload_path: {{ .Values.secrets.apm.data_upload_path | b64enc }}
  data_private_key: {{ .Values.secrets.apm.data_private_key | b64enc }}