apiVersion: v1
kind: Secret
metadata:
  name: "atp-encounter-secret"
type: Opaque
data:
  atp-encounter-username: {{ .Values.global.secrets.atp.encounter.username | b64enc }}
  atp-encounter-password: {{ .Values.global.secrets.atp.encounter.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: "ajdb-encounter-secret"
type: Opaque
data:
  ajdb-encounter-username: {{ .Values.global.secrets.ajdb.encounter.username | b64enc }}
  ajdb-encounter-password: {{ .Values.global.secrets.ajdb.encounter.password | b64enc }}