apiVersion: v1
kind: Secret
metadata:
  name: "uho-streampool"
  namespace: uho
type: Opaque
data:
  bootstrap-servers: {{ .Values.secrets.stream.bootstrap_servers | b64enc }}
  sasl-connection-instance-principal: {{ .Values.secrets.stream.sasl_connection_instance_principal | b64enc }}
  appointment-messages-stream: {{ .Values.secrets.stream.appointment_messages_stream | b64enc }}
  patient-events-stream: {{ .Values.secrets.stream.patient_events_stream | b64enc }}
  followup-messages-stream: {{ .Values.secrets.stream.followup_messages_stream | b64enc }}
  feedback-messages-stream: {{ .Values.secrets.stream.feedback_messages_stream | b64enc }}
  encounter-messages-stream: {{ .Values.secrets.stream.encounter_messages_stream | b64enc }}
  appointment-messages-stream-id: {{ .Values.secrets.stream.appointment_messages_stream_id | b64enc }}
  patient-messages-stream-id: {{ .Values.secrets.stream.patient_messages_stream_id | b64enc }}
  endpoint: {{ .Values.secrets.stream.endpoint | b64enc }}

