micronaut:
  application:
    name: patient
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
      roles-name: "scope"
    endpoints:
      logout:
        enabled: true
        get-allowed: true
    intercept-url-map-prepend-pattern-with-context-path: false
    intercept-url-map:
      - pattern: /v1/patients/*/actions/authorizeDevice
        httpMethod: POST
        access:
          - /patient
      - pattern: /v1/patients
        httpMethod: POST
        access:
          - /service
      - pattern: /v1/patients/*
        httpMethod: DELETE
        access:
          - /service
      - pattern: /v1/patients/*
        httpMethod: GET
        access:
          - /patient
          - /provider
          - /service
      - pattern: /v1/patients/username/*
        httpMethod: GET
        access:
          - /patient
          - /provider
      - pattern: /v1/patients/actions/search
        httpMethod: GET
        access:
          - /provider
      - pattern: /v1/patients/*
        httpMethod: PUT
        access:
          - /patient
          - /service
    enabled: false

  metrics:
    enabled: false
    export:
      oraclecloud:
        enabled: true
        namespace: uho_${micronaut.application.name}
        resourceGroup: mn_local
        compartmentId: #<Add compartment id here where metrics need to be posted>

liquibase:
  datasources:
    default:
      parameters:
        prefix: dev

streaming:
  id:
  endpoint:

oci:
  config:
    profile: DEFAULT

service:
  provider: "http://provider"