micronaut:
  application:
    name: patient
  security:
    enabled: false
    token:
      enabled: false
      jwt:
        enabled: false
  metrics:
    enabled: false

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''

streaming:
  id: ""
  endpoint: ""
