apiVersion: v1
kind: Secret
metadata:
  name: "atp-connection"
  namespace: uho
type: Opaque
data:
  atp-wallet-password: {{ .Values.secrets.atp.connection.wallet_password | b64enc }}
  atp-service: {{ .Values.secrets.atp.connection.atp_service | b64enc }}