apiVersion: v1
kind: Secret
metadata:
  name: "atp-provider-secret"
type: Opaque
data:
  atp-provider-username: {{ .Values.global.secrets.atp.provider.username | b64enc }}
  atp-provider-password: {{ .Values.global.secrets.atp.provider.password | b64enc }}