apiVersion: v1
kind: Secret
metadata:
  name: "atp-appointment-secret"
type: Opaque
data:
  atp-appointment-username: {{ .Values.global.secrets.atp.appointment.username | b64enc }}
  atp-appointment-password: {{ .Values.global.secrets.atp.appointment.password | b64enc }}